### ISSUE TITLE
Add TypeScript

### ISSUE THREAD

**Issue by helloitsjoe** [helloitsjoe/react-hooks-compose#2]
Either convert library to TS or add @types.

**Comment by BatuhanW** [comment]
I Would like to convert to typescript @helloitsjoe

**Comment by helloitsjoe** [comment]
@BatuhanW Sounds great, you're welcome to submit a PR!

**Comment by BatuhanW** [comment]
I will send one this week then.

**Comment by BatuhanW** [comment]
@helloitsjoe I was too busy last week, I'll be able to send PR this weekend. I already started but it's incomplete yet.

**Comment by helloitsjoe** [comment]
@BatuhanW Not a problem, no rush!

**Comment by ThanhNghia944** [comment]
waiting .... ^^

**Comment by juicylevel** [comment]
when is the release planned?

**Comment by helloitsjoe** [comment]
I don't have any plans to convert this library to TypeScript right now. Feel free to contribute type definitions to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)!

**Comment by HamadTheIronside** [comment]
Hey @helloitsjoe
I'm planning to use this library and I would love to contribute and convert it to typescript

**Comment by paulcarroll** [comment]
Hey @helloitsjoe and @HamadTheIronside , I also wanted TS types and just added Definitely Typed project for react-hooks-compose, please see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69720

Are you ok with the type definition Joe, or have any changes to request?

If everything is good, can I either you as a co-owner of the type library? (as DT prefers having two owners per project)
