### ISSUE TITLE
 unable to resolve dependency tree

### ISSUE THREAD

**Issue by tariqproxym** [helloitsjoe/react-hooks-compose#25]
i have this issue while trying to install the package 
 unable to resolve dependency tree

npm ERR! While resolving: DemoProject@0.0.1
npm ERR! Found: **react@18.0.0**
npm ERR! node_modules/react
npm ERR!   react@"18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer **react@"^16.8"** from react-hooks-compose@2.0.18
npm ERR! node_modules/react-hooks-compose
npm ERR!   react-hooks-compose@"*" from the root project

**Comment by helloitsjoe** [comment]
Thanks for reporting! Will fix shortly.
