### ISSUE TITLE
Usage with zustand slice

### ISSUE THREAD

**Issue by KrisLau** [helloitsjoe/react-hooks-compose#31]
Thank you for this package! So zustand is a hook based state management library and they have a method to [subscribe to only individual states within a store](https://github.com/pmndrs/zustand) like this:
```js
const nuts = useBearStore((state) => state.nuts)
const honey = useBearStore((state) => state.honey)
```
Which helps to avoid unnecessary re-renders.

I tried to use this method with `react-hook-compose` but I couldn't seem to get it working. What I've tried so far:
```js
composeHooks({useBearStore((state) => state.nuts})
```
```js
composeHooks({value: () => useBearStore((state) => state.nuts})
```

Any ideas as to what I could do to implement this?

**Comment by helloitsjoe** [comment]
Hello! I haven't used Zustand but I can investigate this. Do you have a minimal reproducible example, for example a [CodeSandbox](https://codesandbox.io/) or [StackBlitz](https://stackblitz.com/) link?

**Comment by KrisLau** [comment]
Thanks for the quick reply! Made a simple Expo Snack with both [`zustand`](https://github.com/pmndrs/zustand) and `react-hooks-compose` for you: https://snack.expo.dev/@kris_lau/zustand-react-hooks-compose

**Comment by helloitsjoe** [comment]
Your second example seems to work for me, updated snack here: https://snack.expo.dev/TCRtl9VzM

```javascript
export default composeHooks({ count: () => useStore((state) => state.count) })(App);
```

If I'm missing something, it would be great if you could update your example to show what's not working!

**Comment by KrisLau** [comment]
So when I do it in my project I get the rule of hooks error:
![image](https://user-images.githubusercontent.com/46275463/217000797-62cb6350-92b5-4b24-947e-d44c20834e62.png)
and if I try to do multiple values, I get a `prop already exists` error:
![image](https://user-images.githubusercontent.com/46275463/217001032-c56d905d-5726-47bf-bac1-d567798fe794.png)

**Comment by helloitsjoe** [comment]
In this case the linter can't infer that the hook will be used inside a Component, which is what's causing the rule of hooks error.

You should be able to resolve this in a couple of ways:
1. You can ignore the rules of hooks warning with `// eslint-disable-next-line react-hooks/rules-of-hooks`
2. If you prefer not to disable that eslint rule, you could create wrapper hooks. This will make the rules of hooks happy and will avoid the `prop already exists` error above:

```javascript
export default composeHooks({
    useText: () => ({ text: useStore(state => state.text) }),
    useCount: () => ({ count: useStore(state => state.count) }),
})(Component);
```

I wasn't able to reproduce the `prop already exists` error, and I can't tell much from the screenshot. If that's still happening please send a link to a reproduction of the issue in a Snack, CodeSandbox, CodePen, StackBlitz etc. - somewhere where I can poke around the code.

**Comment by helloitsjoe** [comment]
Did that solve your issue? I'll close this issue if so, otherwise let me know and I'll look into it some more.

**Comment by helloitsjoe** [comment]
Closing, feel free to reopen if this is still unresolved!
