### ISSUE TITLE
Docs example with props has error

### ISSUE THREAD

**Issue by rnz269** [helloitsjoe/react-hooks-compose#5]
const FormContainer = composeHooks(props => ({
  useForm: () => useForm(props.initialValue)
})(FormPresenter);

Parenthesis preceding props (after composeHooks) isn't closed:
composeHooks**(**props

**Comment by rnz269** [comment]
Oddly, the above doesn't seem to throw an error in my eslint, whereas the following does:

export default composeHooks(props => ({
  useGame: () => useGame(props)
}))(Game)

This throws an error: "eslint: error Parsing error: Unexpected token export"

**Comment by helloitsjoe** [comment]
Good catch, thanks! Fixed.
